### ISSUE TITLE
Random color

### ISSUE THREAD

**Issue by djanoris** [videogameboy76/frozenbubbleandroid#33]
Sometimes, when I am shoting in bubbles,  the bullet are changing in random color.

**Comment by videogameboy76** [comment]
I think this issue is related to confusing the "actual" launch bubble on top with the "followup" launch bubble below.  I have heard of this issue before (from my wife, no less) but have never observed it myself.  I have investigated the issue and not been able to reproduce it, but will leave this issue open to investigate further at some point.
